### PR TITLE
Added -auto-orient options

### LINKED ISSUE #4: Rotate portrait image on resize
Hi folks !

I'm using quickthumb in express to resize my pictures.
I've got an issue with portrait images.

Original pictures are in portrait mode, when Quickthumb resize these pictures, it save  theses images in landscape mode.

Obviously, no probleme with Landscape photos :P

### PR DESCRIPTION
**Pull request by AamuLumi**
-auto-orient option in imagemagick avoid to loose EXIF information in image, and keep portrait picture as portrait picture. Resolved #4.
(more info : http://www.imagemagick.org/discourse-server/viewtopic.php?t=12998)

### CODE REVIEW

**Comment by dogusev** [comment]
Hi!
When this will be merged?

**Comment by AamuLumi** [comment]
I don't know. There's some pull requests waiting on this projects. Perhaps this project needs an updated fork with all updates.

**Comment by dogusev** [comment]
By the way, this fix is not stable.
I tried, and images didn't saved at all.
I'll try to provide more info, a bit later

**Comment by zivester** [comment]
@AamuLumi or @dogusev could you provide an example image for which this does/doesn't work?  I appreciate the PR, just would like to verify before its inclusion.

**Comment by dogusev** [comment]
here is an error
 [Error: Command failed: convert.im6: unrecognized option `-auto_orient' @ error/convert.c/ConvertImageCommand/714.
] timedOut: false, killed: false, code: 1, signal: null

and this is the image:

**Comment by AamuLumi** [comment]
I found the (so stupid) error : I wrote "-auto_orient" instead of "-auto-orient".
@dogusev can you check if all is good for you ? I personally test on landscape and portrait picture, and no problem for me.

**Comment by dogusev** [comment]
@AamuLumi  
Seem to be ok now, different orientations and image formats converted correctly!
Thanks!

**Pull request closed without merging**
